#!/bin/bash

echo "Checking for updates..."
HAS_UPDATES=$(curl -X GET 'http://localhost:7062/has_updates?as_html_response=true')
if [ "$HAS_UPDATES" = "True" ]; then
    echo "Updates found, updating..."
elif [ "$HAS_UPDATES" = "False" ]; then
    echo "No updates available. You are up to date."
    exit 0
else 
    echo "Refinery doesn't seem to run. It cannot be checked if any updates are available."
    echo "Do you want to try to update anyway? (y/n)"
    read -r UPDATE_ANYWAY
    if [ "$UPDATE_ANYWAY" == "y" ]; then
        echo "Updating..."
    else
        echo "Exiting..."
        exit 0
    fi
fi

echo "Stopping running containers..."
source stop

echo "Pulling repository from github..."
git checkout release
git pull

echo "Updating kern-refinery python package..."
pip install -U kern-refinery

echo "Pulling newest images of exec envs..."
docker pull kernai/refinery-lf-exec-env:latest
docker pull kernai/refinery-ml-exec-env:latest
docker pull kernai/refinery-record-ide-env:latest

echo "Pulling newest images of refinery..."
docker-compose -f refinery/docker-compose.yml pull

echo "Starting refinery containers..."
source start

echo "Triggering refinery-updater..."
curl -X POST http://localhost:7062/update_to_newest

echo "Refinery has been updated to the latest version and is running on:"
echo "UI:           http://localhost:4455/app/"
echo "Minio:        $MINIO_ENDPOINT"
echo "MailHog:      http://localhost:4436/"